### PR TITLE
Need to create PR manually

### PR DESCRIPTION
**Pull request by rsese**
### Why:

towards https://github.com/github/skills/issues/96

resolves https://github.com/skills/resolve-merge-conflicts/issues/7

because of default Actions settings we need to adjust the course so the learner manually creates a PR

### What's being changed:

* remove use of `gh pr` and ask user to create a PR manually
* add a new step to trigger on the PR creation and then create the merge conflict in this step

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by heiskr — APPROVED** [review]
This looks amazing, totally makes sense to add the extra step for this course :)

**Comment by rsese** [comment]
> This looks amazing, totally makes sense to add the extra step for this course :)

🙇 !  lol it took me a bit, was hoping I could could just remove the `gh pr` part but the flow of the merge conflict stuff seemed like it needed another step in between.

going to test a bit more to make sure it works smoothly 🤞

**Comment by rsese** [comment]
tested again and didn't find any problems 🙌 

@cmwilson21 added you for review since there is a small content change -- basically I needed to add a new intermediate step where we ask the learner to create a PR manually so I moved some of the copy around and I think it reads well but let me know if you have any notes :v:

**Comment by heiskr** [comment]
Content changes seem small enough here that we can go ahead and merge given the urgency, but @skills/content-reviewers feel free to make edits later.

**Pull request merged**
